dependencies:
  #- <organiztion/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0'
dotenv: .env
networks:
  default: development
  rinkeby:
    #eth_usd_price_feed: '0x715658ed825D15A7de93017b92A78DC7343f411A'
    eth_usd_price_feed: '0xd22DDADf82ed03E5EdD3530Cfd879644BCE9CFFc'
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}